### ISSUE TITLE
[question] how to modify command for router OS v6?

### ISSUE THREAD

**Issue by m3dbedb** [akinozgen/go-routeros-live-hotspot-users#1]
For API v6 command looks like

     /ip hotspot active print
but it when I change go-routeros-live-hotspot-users/main.go line 76

    reply, runErr := client.Run("/ip hotspot active print")

I have error

username:~/go/go-routeros-live-hotspot-users$ ./run.sh

    2022/06/29 13:41:14 from RouterOS device: no such command
    exit status 1

**Comment by akinozgen** [comment]
Try removing whitespace from command.
e.g.
```go
reply, runErr := client.Run("/ip/hotspot/active/print")
```

i think this api doesnt support terminal like syntax

please refer to api's documentation and examples
[docs](https://pkg.go.dev/github.com/go-routeros/routeros?utm_source=godoc)
[example](https://github.com/go-routeros/routeros/blob/2a44d57c6730/examples/run/main.go)
